name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:

  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
      # Initialization
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '18'
      - run: npm ci
      - name: Copy configuration
        run: cp config.json.example config.json

      # Run linter
      - name: Lint
        run: npm run lint

      # Create Chrome artifacts
      - name: Create Chrome artifacts
        run: npm run build:chrome
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: ChromeExtension
          path: dist
      - run: mkdir ./builds
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/ChromeExtension.zip ./dist

      # Create Firefox artifacts
      - name: Create Firefox artifacts
        run: npm run build:firefox
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: FirefoxExtension
          path: dist
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/FirefoxExtension.zip ./dist

      # Create Beta artifacts (Builds with the name changed to beta)
      - name: Create Chrome Beta artifacts
        run: npm run build:chrome -- --env stream=beta
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: ChromeExtensionBeta
          path: dist
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/ChromeExtensionBeta.zip ./dist

      - name: Create Firefox Beta artifacts
        run: npm run build:firefox -- --env stream=beta
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: FirefoxExtensionBeta
          path: dist
      - uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        with:
          args: zip -qq -r ./builds/FirefoxExtensionBeta.zip ./dist

