name: update oss attributions
on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-oss:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest 
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: '18'
      - name: Install and generate attribution
        run: |
          npm ci
          npm i -g oss-attribution-generator
          generate-attribution
          mv ./oss-attribution/attribution.txt ./public/oss-attribution/attribution.txt
      - name: Prettify attributions
        run: |
          cd ci && npx ts-node prettify.ts

      - name: Create pull request to update list
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        # v4.2.3
        with:
          commit-message: Update OSS Attribution
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ci/oss_attribution
          title: Update OSS Attribution
          body: Automated OSS Attribution update
