name: update invidious
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # check every month

permissions:
  contents: read

jobs:
  check-list:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest 
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          submodules: recursive
      - name: Download instance list
        run: |
          wget https://api.invidious.io/instances.json -O ci/data.json
      - name: Install dependencies
        run: npm ci
      - name: "Run CI"
        run: npm run ci:invidious

      - name: Create pull request to update list
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04
        # v4.2.3
        with:
          commit-message: Update Invidious List
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: ci/update_invidious_list
          title: Update Invidious List
          body: Automated Invidious list update